In [2]:
import requests
import pandas as pd

headers = {
    "USER_AGENT": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/71.0.3578.80 Chrome/71.0.3578.80 Safari/537.36",
    "referer": "https://fincaraiz.com.co/"
}

json_data = {
    'filter': {
        'offer': {
            'slug': [
                'sell',
            ],
        },
        'property_type': {
            'slug': [
                'apartment',
            ],
        },
        'locations': {
            'location_point':[
                [
                -76.59027692154969,
                3.535311581094419
                ],
                [
                -76.48934003190125,
                3.3689308955117525
                ],
            ],
        },
    },
    'fields': {
        'exclude': [],
        'include': [
            'area',
            'baths.id',
            'baths.name',
            'client.client_type',
            'client.company_name',
            'client.first_name',
            'client.last_name',
            'garages.name',
            'is_new',
            'locations.cities.name',
            'locations.cities.slug',
            'locations.countries.name',
            'locations.countries.slug',
            'locations.groups.name',
            'locations.groups.slug',
            'locations.groups.subgroups.name',
            'locations.groups.subgroups.slug',
            'locations.location_point',
            'locations.neighbourhoods.name',
            'locations.neighbourhoods.slug',
            'locations.states.name',
            'locations.states.slug',
            'locations.view_map.slug',
            'media.floor_plans.count',
            'media.photos.list.id',
            'media.photos.list.image.full_size',
            'media.photos.list.is_main',
            'media.videos.count',
            'min_area',
            'min_price',
            'price',
            'products.configuration.tag_name',
            'products.label',
            'products.name',
            'products.slug',
            'property_id',
            'fr_property_id',
            'rooms.name',
            'title',
            'property_type.name',
            'offer.name',
            'fr_parent_property_id',
        ],
        'limit': 100,
        'offset': 100,
        'ordering': [],
        'platform': 40,
        'with_algorithm': False,
    }
}

response = requests.post('https://api.fincaraiz.com.co/document/api/1.0/listing/search', headers=headers, json=json_data, timeout=10)
data = response.json()

df = pd.DataFrame(data)

df.to_csv("aptos_mde.csv")

df

,took,timed_out,_shards,hits,cache
total,43,False,3.0,"{'value': 7465, 'relation': 'eq'}",NaN
successful,43,False,3.0,NaN,NaN
skipped,43,False,0.0,NaN,NaN
failed,43,False,0.0,NaN,NaN
max_score,43,False,NaN,0.0,NaN
hits,43,False,NaN,"[{'_index': 'fr-site-listing', '_id': 'cbcf4bf...",NaN
id,43,False,NaN,NaN,ListingDocument-90c13ce39b08a3a6940d5d4fc72b3a...
time_type,43,False,NaN,NaN,minutes
time_data,43,False,NaN,NaN,5
datetime,43,False,NaN,NaN,2023-09-13 12:16:16